name: Justin Tran
description: Justin Tran's Blog Posts and Projects
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /blog/:path/
  
  projects:
    output: true
    permalink: /projects/:path/
    
  research:
    output: true
    permalink: /research/:path/
