---
layout: post
title: "Forcing eSports - The Early Missteps of Blizzard's Overwatch League"
date: 2017-08-21
description: As Blizzard's Overwatch League continues to speed ahead, a host of issues threaten to hold the league back
image: /blog/OWL_Logo.png
---
![Overwatch League Logo]( /blog/OWL_Logo.png )*THe official Overwatch League logo courtesy of Blizzard Entertainment*

I think my lack of faith in Overwatch League stems from multiple sources. Keep in mind that I have colleagues actually being hired within the last few weeks to work for Blizzard purely to work on Overwatch League at a variety of levels. While I really want what's best for them in their careers I can't imagine Overwatch League succeeding for a couple of reasons.
First off are the competitive mechanics of Overwatch. I personally don't believe the individual skill ceiling can go much higher than it currently is. The mechanics of the heroes are clearly aimed to bridge a gap between casual and competitive play rather than being geared purely towards difficult to master abilities. I truly believe that for the majority of heroes, the mechanics can be mastered quite easily along with aim due to the fairly generous hitboxes in comparison to other first person-shooters with successful competitive scenes. The professional scene as it is seems to be very geared towards heavy coordination while individual play benefits most from communication and game awareness. It all basically boils down to teamplay without much room for individual outplay due to a slightly lower skill ceiling at the benefit of a more fun game for more casual players (like myself). Again, this point is highly arguable.
Secondly, the Overwatch League's focus on franchising seems to be repudiating the existence of smaller eSports organizations. Just in the last day, Splyce and Complexity have dropped their Overwatch teams completely indicating that the costs to continue their part in Overwatch League to be far too expensive. Is this the next step for eSports in general? I can't say but it's a shame to see smaller organizations that started it all be phased out due to money when they are able to thrive in so many other eSports communities that promote a minor league (ESEA Main, Premier, etc. for Counter Strike and Challenger League in League). Hopefully Blizzard promotes a minor league that smaller organizations can take part in but there's nothing as of now.
As a member of a small eSports community at a university where competitive gaming grew up right in front of us with small LANs for games like Smash, it is strange and disjointed seeing a company trying to promote Overwatch as a competitive game purely within their jurisdiction before even testing the waters of whether or not it has the standing to be a highly competitive eSport. I mean, it's only been a year has been officially released! eSports isn't growing faster than Blizzard can handle, but rate at which Blizzard wants competitive Overwatch to grow is faster than any community can handle. What's even more strange is this community's lack of care for the competitive scene. There are rarely ever any major eSports posts with highlights when teams like Meta Athena are making crazy plays that would impress any player.
I love eSports, but the lack of information combined with the direction they seem to be taking Overwatch League in is in a downward trajectory from my perspective. I'm hoping for the best but expecting the worst because I absolutely love the game and want it to succeed in the eSports world.
